(test
 (name lexer_test)
 (libraries CompilerAssignment)
 (deps (glob_files_rec test_cases/lexer_tests/*)))

(test
 (name parser_test)
 (libraries CompilerAssignment)
 (deps (glob_files_rec test_cases/parser_tests/*)
       (alias runtest-lexer_test)))

(test
 (name type_check_test)
 (libraries CompilerAssignment)
 (deps (glob_files_rec test_cases/type_check_tests/*)
       (alias runtest-parser_test)))

(test
 (name code_gen_test)
 (libraries CompilerAssignment)
 (deps (glob_files_rec test_cases/code_gen_tests/*)
       (alias runtest-type_check_test)))

(test
 (name optimiser_test)
 (libraries CompilerAssignment)
 (deps (glob_files_rec test_cases/optimiser_tests/*)
       (alias runtest-code_gen_test)))