lib: [
  "_build/install/default/lib/CompilerAssignment/CompilerAssignment.a"
  "_build/install/default/lib/CompilerAssignment/CompilerAssignment.cma"
  "_build/install/default/lib/CompilerAssignment/CompilerAssignment.cmxa"
  "_build/install/default/lib/CompilerAssignment/META"
  "_build/install/default/lib/CompilerAssignment/compilerAssignment.cmi"
  "_build/install/default/lib/CompilerAssignment/compilerAssignment.cmt"
  "_build/install/default/lib/CompilerAssignment/compilerAssignment.cmx"
  "_build/install/default/lib/CompilerAssignment/compilerAssignment.ml"
  "_build/install/default/lib/CompilerAssignment/compilerAssignment__Lexer.cmi"
  "_build/install/default/lib/CompilerAssignment/compilerAssignment__Lexer.cmt"
  "_build/install/default/lib/CompilerAssignment/compilerAssignment__Lexer.cmx"
  "_build/install/default/lib/CompilerAssignment/compilerAssignment__Parser.cmi"
  "_build/install/default/lib/CompilerAssignment/compilerAssignment__Parser.cmt"
  "_build/install/default/lib/CompilerAssignment/compilerAssignment__Parser.cmx"
  "_build/install/default/lib/CompilerAssignment/dune-package"
  "_build/install/default/lib/CompilerAssignment/lexer.ml"
  "_build/install/default/lib/CompilerAssignment/opam"
  "_build/install/default/lib/CompilerAssignment/parser.ml"
]
libexec: [
  "_build/install/default/lib/CompilerAssignment/CompilerAssignment.cmxs"
]
bin: [
  "_build/install/default/bin/CompilerAssignment"
]
